AWSTemplateFormatVersion: '2010-09-09'
Description: demo

Resources:
  MyInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-08e3b3155fc937a94
      InstanceType: t3.micro
      KeyName: kdp
      SecurityGroupIds:
        - !Ref MyInstanceSecurityGroup
      Tags:
        - Key: Name
          Value: second pipeline server