AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyCustomIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: ['ec2.amazonaws.com']
            Action: ['sts:AssumeRole']
      Policies:
        - PolicyName: 's3-policy-2pm'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action: ['s3:GetObject', 's3:ListBucket', 's3:PutObject', 's3:DeleteObject']
                
                